name: "Delete UAT deployment"
description: 'Deletes a UAT deployment with a name mathcing the merged/closed branch'
inputs:
  k8s_cluster:
    description: "Kubernetes cluster name"
    required: true
  k8s_cluster_cert:
    description: "Kubernete cluster certificate"
    required: true
  k8s_namespace:
    description: "Kubernetes cluster namespace"
    required: true
  k8s_token:
    description: "Kubernetes authentication token"
    required: true
  release_name_prefix:
    required: false
outputs:
  branch-name:
    description: "Extracted branch name"
    value: ${{ steps.extract_branch.outputs.branch_name }}
  release-name:
    description: "Extracted release name"
    value: ${{ steps.extract_release.outputs.release_name }}
  delete-message:
    description: "Extracted release name"
    value: ${{ steps.delete_release.outputs.message }}

runs:
  using: "composite"
  steps:
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        if [ $GITHUB_EVENT_NAME == "pull_request" ]
        then
          branch=$GITHUB_HEAD_REF
        else
          branch=${GITHUB_REF#refs/heads/}
        fi

        echo "branch_name=$branch" >> $GITHUB_OUTPUT

    - name: Extract release name
      id: extract_release
      shell: bash
      run: |
        branch_name=${{ steps.extract_branch.outputs.branch_name }}
        truncated_branch=$(echo $branch_name | tr '[:upper:]' '[:lower:]' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | cut -c1-30 | sed 's/-$//')
        prefix=${{ inputs.release_name_prefix }}

        echo "release_name=${prefix}${truncated_branch}" >> $GITHUB_OUTPUT

    - name: Authenticate to the cluster
      id: authenticate_to_cluster
      shell: bash
      env:
        K8S_CLUSTER: ${{ inputs.k8s_cluster }}
        K8S_CLUSTER_CERT: ${{ inputs.k8s_cluster_cert }}
        K8S_NAMESPACE: ${{ inputs.k8s_namespace }}
        K8S_TOKEN: ${{ inputs.k8s_token }}
      run: |
        echo "${K8S_CLUSTER_CERT}" > ./ca.crt
        kubectl config set-cluster ${K8S_CLUSTER} --certificate-authority=./ca.crt --server=https://${K8S_CLUSTER}
        kubectl config set-credentials github-action --token=${K8S_TOKEN}
        kubectl config set-context ${K8S_CLUSTER} --cluster=${K8S_CLUSTER} --user=github-action --namespace=${K8S_NAMESPACE}
        kubectl config use-context ${K8S_CLUSTER}

    - name: Delete UAT release
      id: delete_release
      shell: bash
      run: |
        release_name=${{ steps.extract_release.outputs.release_name }}
        found=$(helm list --all | grep $release_name || [[ $? == 1 ]])

        if [[ ! -z "$found" ]]
        then
          helm delete $release_name
          echo "message=$(echo "Deleted UAT release ${release_name}!")" >> $GITHUB_OUTPUT
        else
          echo "message=$(echo "UAT release, ${release_name}, not found!")" >> $GITHUB_OUTPUT
        fi
